services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/salesDB

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: